### PR TITLE
Prepare for cran release of dynutils 1.0.2

### PR DESCRIPTION
**Pull request by rcannood**
* BUG FIX: Fix generation of error messages in `%all_in%`.
 
 * FUNCTIONALITY: Added `read_h5()` and `write_h5()` functions.
 
 * FUNCTIONALITY: Added `is_sparse()`.
 
 * FUNCTIONALITY: Added `update_news()` and `recent_news()`. So meta!
 
 * FUNCTIONALITY: Moved `calculate_mean()` from dyneval to dynutils.

### CODE REVIEW

**Comment by zouter** [comment]
Waiting for this to merge for dynguidelines

**Comment by rcannood** [comment]
I'm working as fast as I can ö ;)

( I'm not angry, but I am typing as fast as I can ;) )

**Comment by zouter** [comment]
Hurry hurry! The whole dynverse is falling apart on travis :grin:

**Comment by rcannood** [comment]
I'm pretty much already turning into a poly(A) tail here

**Comment by rcannood** [comment]
> AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

─ me

**Comment by zouter** [comment]
Let's merge this :1st_place_medal: !

**Comment by rcannood** [comment]
must... increase.. codecov!

**Comment by rcannood** [comment]
purrfection

**Comment by zouter** [comment]
image

**Comment by zouter** [comment]
Here's a present for ya!

**Pull request merged**
